project:
  type: website
  output-dir: docs

website:
  title: "Análisis Oceanográfico"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Objetivos"
        href: objetivos.qmd
      - text: "Equipo"
        href: equipo.qmd
      - text: "Resultados"
        href: resultados.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true


