project:
  type: website
  output-dir: docs

website:
  title: "Análisis Oceanográfico"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Metodología"
        href: about.qmd
      - text: "Datos"
        href: data.qmd
      - text: "Análisis"
        href: analysis.qmd
      - text: "Equipo"
        href: team.qmd
      - text: "Referencias"
        href: references.qmd
  page-navigation: true

execute:
  enabled: true
  echo: false  # show the code
  output: true
  eval: true

format:
  html:
    theme: cosmo
    toc: true


