project:
  type: website

website:
  title: "Analisis Estadistico de Oceanografia del Golfo de California"
  navbar:
    background: primary
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Datos y Metodología"
        file: 01_datos_metodologia.qmd
      - text: "Clustering"
        file: 02_clustering_ang.qmd
      - text: "Frecuencias Dominantes"
        file: 03_frecuencia_chuy.qmd
      - text: "Gradiente Inverso"
        file: 04_gradiente_fede.qmd
      - text: "Modelo Prophet"
        file: 05_prophet_manuel.qmd
      - text: "PCA y Análisis Exploratorio"
        file: 06_pca_elfer.qmd
      - text: "Conclusiones"
        file: 07_conclusiones.qmd
execute:
  enabled: true
  echo: false  # show the code
  output: true
  eval: true

format:
  html:
    theme: cosmo
    toc: true


